// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/subscription/application.proto

package org.wso2.apk.enforcer.discovery.subscription;

public interface ApplicationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wso2.discovery.subscription.Application)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string eventId = 1;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string eventId = 1;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string uuid = 3;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 3;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>string owner = 4;</code>
   * @return The owner.
   */
  java.lang.String getOwner();
  /**
   * <code>string owner = 4;</code>
   * @return The bytes for owner.
   */
  com.google.protobuf.ByteString
      getOwnerBytes();

  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */
  int getAttributesCount();
  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */
  boolean containsAttributes(
      java.lang.String key);
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAttributes();
  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAttributesMap();
  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */

  java.lang.String getAttributesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */

  java.lang.String getAttributesOrThrow(
      java.lang.String key);

  /**
   * <code>.wso2.discovery.subscription.SecuritySchemes securitySchemes = 6;</code>
   * @return Whether the securitySchemes field is set.
   */
  boolean hasSecuritySchemes();
  /**
   * <code>.wso2.discovery.subscription.SecuritySchemes securitySchemes = 6;</code>
   * @return The securitySchemes.
   */
  org.wso2.apk.enforcer.discovery.subscription.SecuritySchemes getSecuritySchemes();
  /**
   * <code>.wso2.discovery.subscription.SecuritySchemes securitySchemes = 6;</code>
   */
  org.wso2.apk.enforcer.discovery.subscription.SecuritySchemesOrBuilder getSecuritySchemesOrBuilder();
}
