// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/subscription/application_key_mapping.proto

package org.wso2.apk.enforcer.discovery.subscription;

public interface ApplicationKeyMappingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wso2.discovery.subscription.ApplicationKeyMapping)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string applicationIdentifier = 1;</code>
   * @return The applicationIdentifier.
   */
  java.lang.String getApplicationIdentifier();
  /**
   * <code>string applicationIdentifier = 1;</code>
   * @return The bytes for applicationIdentifier.
   */
  com.google.protobuf.ByteString
      getApplicationIdentifierBytes();

  /**
   * <code>string keyType = 2;</code>
   * @return The keyType.
   */
  java.lang.String getKeyType();
  /**
   * <code>string keyType = 2;</code>
   * @return The bytes for keyType.
   */
  com.google.protobuf.ByteString
      getKeyTypeBytes();

  /**
   * <code>string envId = 3;</code>
   * @return The envId.
   */
  java.lang.String getEnvId();
  /**
   * <code>string envId = 3;</code>
   * @return The bytes for envId.
   */
  com.google.protobuf.ByteString
      getEnvIdBytes();

  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>string applicationUUID = 5;</code>
   * @return The applicationUUID.
   */
  java.lang.String getApplicationUUID();
  /**
   * <code>string applicationUUID = 5;</code>
   * @return The bytes for applicationUUID.
   */
  com.google.protobuf.ByteString
      getApplicationUUIDBytes();
}
