// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/subscription/application.proto

package org.wso2.apk.enforcer.discovery.subscription;

/**
 * Protobuf type {@code wso2.discovery.subscription.AuthenticationOption}
 */
public final class AuthenticationOption extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wso2.discovery.subscription.AuthenticationOption)
    AuthenticationOptionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AuthenticationOption.newBuilder() to construct.
  private AuthenticationOption(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AuthenticationOption() {
    type_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AuthenticationOption();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AuthenticationOption(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 18: {
            org.wso2.apk.enforcer.discovery.subscription.OAuth2.Builder subBuilder = null;
            if (oAuth2_ != null) {
              subBuilder = oAuth2_.toBuilder();
            }
            oAuth2_ = input.readMessage(org.wso2.apk.enforcer.discovery.subscription.OAuth2.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(oAuth2_);
              oAuth2_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.wso2.apk.enforcer.discovery.subscription.ApplicationProto.internal_static_wso2_discovery_subscription_AuthenticationOption_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.wso2.apk.enforcer.discovery.subscription.ApplicationProto.internal_static_wso2_discovery_subscription_AuthenticationOption_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption.class, org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object type_;
  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OAUTH2_FIELD_NUMBER = 2;
  private org.wso2.apk.enforcer.discovery.subscription.OAuth2 oAuth2_;
  /**
   * <pre>
   * MTLS mTLS = 3;
   * BasicAuth basicAuth = 4;
   * APIKey apiKey = 5;
   * IPRange IPRange = 6;
   * </pre>
   *
   * <code>.wso2.discovery.subscription.OAuth2 oAuth2 = 2;</code>
   * @return Whether the oAuth2 field is set.
   */
  @java.lang.Override
  public boolean hasOAuth2() {
    return oAuth2_ != null;
  }
  /**
   * <pre>
   * MTLS mTLS = 3;
   * BasicAuth basicAuth = 4;
   * APIKey apiKey = 5;
   * IPRange IPRange = 6;
   * </pre>
   *
   * <code>.wso2.discovery.subscription.OAuth2 oAuth2 = 2;</code>
   * @return The oAuth2.
   */
  @java.lang.Override
  public org.wso2.apk.enforcer.discovery.subscription.OAuth2 getOAuth2() {
    return oAuth2_ == null ? org.wso2.apk.enforcer.discovery.subscription.OAuth2.getDefaultInstance() : oAuth2_;
  }
  /**
   * <pre>
   * MTLS mTLS = 3;
   * BasicAuth basicAuth = 4;
   * APIKey apiKey = 5;
   * IPRange IPRange = 6;
   * </pre>
   *
   * <code>.wso2.discovery.subscription.OAuth2 oAuth2 = 2;</code>
   */
  @java.lang.Override
  public org.wso2.apk.enforcer.discovery.subscription.OAuth2OrBuilder getOAuth2OrBuilder() {
    return getOAuth2();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    if (oAuth2_ != null) {
      output.writeMessage(2, getOAuth2());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    if (oAuth2_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOAuth2());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption)) {
      return super.equals(obj);
    }
    org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption other = (org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption) obj;

    if (!getType()
        .equals(other.getType())) return false;
    if (hasOAuth2() != other.hasOAuth2()) return false;
    if (hasOAuth2()) {
      if (!getOAuth2()
          .equals(other.getOAuth2())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    if (hasOAuth2()) {
      hash = (37 * hash) + OAUTH2_FIELD_NUMBER;
      hash = (53 * hash) + getOAuth2().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code wso2.discovery.subscription.AuthenticationOption}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wso2.discovery.subscription.AuthenticationOption)
      org.wso2.apk.enforcer.discovery.subscription.AuthenticationOptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wso2.apk.enforcer.discovery.subscription.ApplicationProto.internal_static_wso2_discovery_subscription_AuthenticationOption_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wso2.apk.enforcer.discovery.subscription.ApplicationProto.internal_static_wso2_discovery_subscription_AuthenticationOption_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption.class, org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption.Builder.class);
    }

    // Construct using org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = "";

      if (oAuth2Builder_ == null) {
        oAuth2_ = null;
      } else {
        oAuth2_ = null;
        oAuth2Builder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.wso2.apk.enforcer.discovery.subscription.ApplicationProto.internal_static_wso2_discovery_subscription_AuthenticationOption_descriptor;
    }

    @java.lang.Override
    public org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption getDefaultInstanceForType() {
      return org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption.getDefaultInstance();
    }

    @java.lang.Override
    public org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption build() {
      org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption buildPartial() {
      org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption result = new org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption(this);
      result.type_ = type_;
      if (oAuth2Builder_ == null) {
        result.oAuth2_ = oAuth2_;
      } else {
        result.oAuth2_ = oAuth2Builder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption) {
        return mergeFrom((org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption other) {
      if (other == org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (other.hasOAuth2()) {
        mergeOAuth2(other.getOAuth2());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string type = 1;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private org.wso2.apk.enforcer.discovery.subscription.OAuth2 oAuth2_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.wso2.apk.enforcer.discovery.subscription.OAuth2, org.wso2.apk.enforcer.discovery.subscription.OAuth2.Builder, org.wso2.apk.enforcer.discovery.subscription.OAuth2OrBuilder> oAuth2Builder_;
    /**
     * <pre>
     * MTLS mTLS = 3;
     * BasicAuth basicAuth = 4;
     * APIKey apiKey = 5;
     * IPRange IPRange = 6;
     * </pre>
     *
     * <code>.wso2.discovery.subscription.OAuth2 oAuth2 = 2;</code>
     * @return Whether the oAuth2 field is set.
     */
    public boolean hasOAuth2() {
      return oAuth2Builder_ != null || oAuth2_ != null;
    }
    /**
     * <pre>
     * MTLS mTLS = 3;
     * BasicAuth basicAuth = 4;
     * APIKey apiKey = 5;
     * IPRange IPRange = 6;
     * </pre>
     *
     * <code>.wso2.discovery.subscription.OAuth2 oAuth2 = 2;</code>
     * @return The oAuth2.
     */
    public org.wso2.apk.enforcer.discovery.subscription.OAuth2 getOAuth2() {
      if (oAuth2Builder_ == null) {
        return oAuth2_ == null ? org.wso2.apk.enforcer.discovery.subscription.OAuth2.getDefaultInstance() : oAuth2_;
      } else {
        return oAuth2Builder_.getMessage();
      }
    }
    /**
     * <pre>
     * MTLS mTLS = 3;
     * BasicAuth basicAuth = 4;
     * APIKey apiKey = 5;
     * IPRange IPRange = 6;
     * </pre>
     *
     * <code>.wso2.discovery.subscription.OAuth2 oAuth2 = 2;</code>
     */
    public Builder setOAuth2(org.wso2.apk.enforcer.discovery.subscription.OAuth2 value) {
      if (oAuth2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        oAuth2_ = value;
        onChanged();
      } else {
        oAuth2Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * MTLS mTLS = 3;
     * BasicAuth basicAuth = 4;
     * APIKey apiKey = 5;
     * IPRange IPRange = 6;
     * </pre>
     *
     * <code>.wso2.discovery.subscription.OAuth2 oAuth2 = 2;</code>
     */
    public Builder setOAuth2(
        org.wso2.apk.enforcer.discovery.subscription.OAuth2.Builder builderForValue) {
      if (oAuth2Builder_ == null) {
        oAuth2_ = builderForValue.build();
        onChanged();
      } else {
        oAuth2Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * MTLS mTLS = 3;
     * BasicAuth basicAuth = 4;
     * APIKey apiKey = 5;
     * IPRange IPRange = 6;
     * </pre>
     *
     * <code>.wso2.discovery.subscription.OAuth2 oAuth2 = 2;</code>
     */
    public Builder mergeOAuth2(org.wso2.apk.enforcer.discovery.subscription.OAuth2 value) {
      if (oAuth2Builder_ == null) {
        if (oAuth2_ != null) {
          oAuth2_ =
            org.wso2.apk.enforcer.discovery.subscription.OAuth2.newBuilder(oAuth2_).mergeFrom(value).buildPartial();
        } else {
          oAuth2_ = value;
        }
        onChanged();
      } else {
        oAuth2Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * MTLS mTLS = 3;
     * BasicAuth basicAuth = 4;
     * APIKey apiKey = 5;
     * IPRange IPRange = 6;
     * </pre>
     *
     * <code>.wso2.discovery.subscription.OAuth2 oAuth2 = 2;</code>
     */
    public Builder clearOAuth2() {
      if (oAuth2Builder_ == null) {
        oAuth2_ = null;
        onChanged();
      } else {
        oAuth2_ = null;
        oAuth2Builder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * MTLS mTLS = 3;
     * BasicAuth basicAuth = 4;
     * APIKey apiKey = 5;
     * IPRange IPRange = 6;
     * </pre>
     *
     * <code>.wso2.discovery.subscription.OAuth2 oAuth2 = 2;</code>
     */
    public org.wso2.apk.enforcer.discovery.subscription.OAuth2.Builder getOAuth2Builder() {
      
      onChanged();
      return getOAuth2FieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * MTLS mTLS = 3;
     * BasicAuth basicAuth = 4;
     * APIKey apiKey = 5;
     * IPRange IPRange = 6;
     * </pre>
     *
     * <code>.wso2.discovery.subscription.OAuth2 oAuth2 = 2;</code>
     */
    public org.wso2.apk.enforcer.discovery.subscription.OAuth2OrBuilder getOAuth2OrBuilder() {
      if (oAuth2Builder_ != null) {
        return oAuth2Builder_.getMessageOrBuilder();
      } else {
        return oAuth2_ == null ?
            org.wso2.apk.enforcer.discovery.subscription.OAuth2.getDefaultInstance() : oAuth2_;
      }
    }
    /**
     * <pre>
     * MTLS mTLS = 3;
     * BasicAuth basicAuth = 4;
     * APIKey apiKey = 5;
     * IPRange IPRange = 6;
     * </pre>
     *
     * <code>.wso2.discovery.subscription.OAuth2 oAuth2 = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.wso2.apk.enforcer.discovery.subscription.OAuth2, org.wso2.apk.enforcer.discovery.subscription.OAuth2.Builder, org.wso2.apk.enforcer.discovery.subscription.OAuth2OrBuilder> 
        getOAuth2FieldBuilder() {
      if (oAuth2Builder_ == null) {
        oAuth2Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.wso2.apk.enforcer.discovery.subscription.OAuth2, org.wso2.apk.enforcer.discovery.subscription.OAuth2.Builder, org.wso2.apk.enforcer.discovery.subscription.OAuth2OrBuilder>(
                getOAuth2(),
                getParentForChildren(),
                isClean());
        oAuth2_ = null;
      }
      return oAuth2Builder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wso2.discovery.subscription.AuthenticationOption)
  }

  // @@protoc_insertion_point(class_scope:wso2.discovery.subscription.AuthenticationOption)
  private static final org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption();
  }

  public static org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AuthenticationOption>
      PARSER = new com.google.protobuf.AbstractParser<AuthenticationOption>() {
    @java.lang.Override
    public AuthenticationOption parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AuthenticationOption(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AuthenticationOption> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AuthenticationOption> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.wso2.apk.enforcer.discovery.subscription.AuthenticationOption getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

