// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/subscription/application.proto

package org.wso2.apk.enforcer.discovery.subscription;

public interface EnvironmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wso2.discovery.subscription.Environment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string envId = 1;</code>
   * @return The envId.
   */
  java.lang.String getEnvId();
  /**
   * <code>string envId = 1;</code>
   * @return The bytes for envId.
   */
  com.google.protobuf.ByteString
      getEnvIdBytes();

  /**
   * <code>string appId = 2;</code>
   * @return The appId.
   */
  java.lang.String getAppId();
  /**
   * <code>string appId = 2;</code>
   * @return The bytes for appId.
   */
  com.google.protobuf.ByteString
      getAppIdBytes();

  /**
   * <code>string keyType = 3;</code>
   * @return The keyType.
   */
  java.lang.String getKeyType();
  /**
   * <code>string keyType = 3;</code>
   * @return The bytes for keyType.
   */
  com.google.protobuf.ByteString
      getKeyTypeBytes();
}
