// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/subscription/application.proto

package org.wso2.apk.enforcer.discovery.subscription;

public interface OAuth2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:wso2.discovery.subscription.OAuth2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string consumerKey = 1;</code>
   * @return The consumerKey.
   */
  java.lang.String getConsumerKey();
  /**
   * <code>string consumerKey = 1;</code>
   * @return The bytes for consumerKey.
   */
  com.google.protobuf.ByteString
      getConsumerKeyBytes();

  /**
   * <code>string keyManager = 2;</code>
   * @return The keyManager.
   */
  java.lang.String getKeyManager();
  /**
   * <code>string keyManager = 2;</code>
   * @return The bytes for keyManager.
   */
  com.google.protobuf.ByteString
      getKeyManagerBytes();

  /**
   * <code>string keyType = 3;</code>
   * @return The keyType.
   */
  java.lang.String getKeyType();
  /**
   * <code>string keyType = 3;</code>
   * @return The bytes for keyType.
   */
  com.google.protobuf.ByteString
      getKeyTypeBytes();
}
