// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/subscription/subscription.proto

package org.wso2.apk.enforcer.discovery.subscription;

public interface SubscriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wso2.discovery.subscription.Subscription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string eventId = 1;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string eventId = 1;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>string subStatus = 2;</code>
   * @return The subStatus.
   */
  java.lang.String getSubStatus();
  /**
   * <code>string subStatus = 2;</code>
   * @return The bytes for subStatus.
   */
  com.google.protobuf.ByteString
      getSubStatusBytes();

  /**
   * <code>string uuid = 3;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 3;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>string timeStamp = 4;</code>
   * @return The timeStamp.
   */
  java.lang.String getTimeStamp();
  /**
   * <code>string timeStamp = 4;</code>
   * @return The bytes for timeStamp.
   */
  com.google.protobuf.ByteString
      getTimeStampBytes();

  /**
   * <code>string organization = 5;</code>
   * @return The organization.
   */
  java.lang.String getOrganization();
  /**
   * <code>string organization = 5;</code>
   * @return The bytes for organization.
   */
  com.google.protobuf.ByteString
      getOrganizationBytes();

  /**
   * <code>repeated .wso2.discovery.subscription.API apis = 6;</code>
   */
  java.util.List<org.wso2.apk.enforcer.discovery.subscription.API> 
      getApisList();
  /**
   * <code>repeated .wso2.discovery.subscription.API apis = 6;</code>
   */
  org.wso2.apk.enforcer.discovery.subscription.API getApis(int index);
  /**
   * <code>repeated .wso2.discovery.subscription.API apis = 6;</code>
   */
  int getApisCount();
  /**
   * <code>repeated .wso2.discovery.subscription.API apis = 6;</code>
   */
  java.util.List<? extends org.wso2.apk.enforcer.discovery.subscription.APIOrBuilder> 
      getApisOrBuilderList();
  /**
   * <code>repeated .wso2.discovery.subscription.API apis = 6;</code>
   */
  org.wso2.apk.enforcer.discovery.subscription.APIOrBuilder getApisOrBuilder(
      int index);
}
