// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/subscription/subscription.proto

package org.wso2.apk.enforcer.discovery.subscription;

public interface SubscriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wso2.discovery.subscription.Subscription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string eventId = 1;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string eventId = 1;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>string subStatus = 2;</code>
   * @return The subStatus.
   */
  java.lang.String getSubStatus();
  /**
   * <code>string subStatus = 2;</code>
   * @return The bytes for subStatus.
   */
  com.google.protobuf.ByteString
      getSubStatusBytes();

  /**
   * <code>string uuid = 3;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 3;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>string organization = 4;</code>
   * @return The organization.
   */
  java.lang.String getOrganization();
  /**
   * <code>string organization = 4;</code>
   * @return The bytes for organization.
   */
  com.google.protobuf.ByteString
      getOrganizationBytes();

  /**
   * <code>.wso2.discovery.subscription.SubscribedAPI subscribedApi = 5;</code>
   * @return Whether the subscribedApi field is set.
   */
  boolean hasSubscribedApi();
  /**
   * <code>.wso2.discovery.subscription.SubscribedAPI subscribedApi = 5;</code>
   * @return The subscribedApi.
   */
  org.wso2.apk.enforcer.discovery.subscription.SubscribedAPI getSubscribedApi();
  /**
   * <code>.wso2.discovery.subscription.SubscribedAPI subscribedApi = 5;</code>
   */
  org.wso2.apk.enforcer.discovery.subscription.SubscribedAPIOrBuilder getSubscribedApiOrBuilder();

  /**
   * <code>string timeStamp = 6;</code>
   * @return The timeStamp.
   */
  java.lang.String getTimeStamp();
  /**
   * <code>string timeStamp = 6;</code>
   * @return The bytes for timeStamp.
   */
  com.google.protobuf.ByteString
      getTimeStampBytes();
}
