# permissions for end users to edit applicationmappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: applicationmapping-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: applicationmapping-editor-role
rules:
- apiGroups:
  - cp.wso2.com
  resources:
  - applicationmappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cp.wso2.com
  resources:
  - applicationmappings/status
  verbs:
  - get
